name: PRD Build
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run export

      - name: Deploy
        uses: reggionick/s3-deploy@v2
        with:
          folder: out
          bucket: ${{ secrets.S3_PRD_BUCKET }}
          bucket-region: ${{ secrets.S3_PRD_BUCKET_REGION }}
          dist-id: ${{ secrets.PRD_CLOUDFRONT_DISTRIBUTION_ID }}
