name: QA Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run export

      - name: Deploy
        uses: reggionick/s3-deploy@v2
        with:
          folder: out
          bucket: ${{ secrets.S3_QA_BUCKET }}
          bucket-region: ${{ secrets.S3_QA_BUCKET_REGION }}
          dist-id: ${{ secrets.QA_CLOUDFRONT_DISTRIBUTION_ID }}
          